/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import io.DatabaseMethods;
import io.DatabaseBackup;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * Main window GUI for the Vendor Database program.
 * @author Link Jones
 * @version 1.0
 * @since 2021-11-24
 */
public class MainGUI extends javax.swing.JFrame
{
    private static final String HELPDOC = "User Documentation.pdf";
    /**
     * Creates new form MainGuiForm
     */
    public MainGUI()
    {
        initComponents();
        try //try to load database
        {
            DatabaseMethods.createTables();
        }
        catch (Exception ex) //lock the display if database fails to load
        { 
            disableButtons();
            lblFeedback.setText("Unable to load database");
            System.err.println("Unable to load database");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton2 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        imgIcon = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnViewVendors = new javax.swing.JButton();
        btnAddVendor = new javax.swing.JButton();
        btnBackUpData = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        lblTitle.setText("Craft Market Vendor Registration");

        imgIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_icon.png"))); // NOI18N
        imgIcon.setToolTipText("");

        lblFeedback.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblFeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnViewVendors.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnViewVendors.setText("View Vendors");
        btnViewVendors.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewVendorsActionPerformed(evt);
            }
        });

        btnAddVendor.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnAddVendor.setText("Add Vendor");
        btnAddVendor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddVendorActionPerformed(evt);
            }
        });

        btnBackUpData.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnBackUpData.setText("Back Up Data");
        btnBackUpData.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackUpDataActionPerformed(evt);
            }
        });

        btnHelp.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHelpActionPerformed(evt);
            }
        });

        btnRestore.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnRestore.setText("Restore Data");
        btnRestore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackUpData, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewVendors, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnViewVendors, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackUpData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle)
                    .addComponent(imgIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addComponent(imgIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblFeedback)
                .addContainerGap())
        );

        imgIcon.getAccessibleContext().setAccessibleName("Market Icon");
        imgIcon.getAccessibleContext().setAccessibleDescription("Image of a cartoon craft market stall");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Opens the Add Vendor window. Hides this window.
     * @param evt ActionEvent, passed by default but not used
     */
    private void btnAddVendorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddVendorActionPerformed
    {//GEN-HEADEREND:event_btnAddVendorActionPerformed
        AddVendor newWindow = new AddVendor(this);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddVendorActionPerformed
    /**
     * Back up database to a binary object file. Asks for confirmation from the user.
     * @param evt ActionEvent, passed by default but not used
     */
    private void btnBackUpDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackUpDataActionPerformed
    {//GEN-HEADEREND:event_btnBackUpDataActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, 
                                            "Back up the database?", 
                                            "Confirm", 
                                            JOptionPane.YES_NO_OPTION);
        if (choice == 0)
        {    
            if (DatabaseBackup.writeToFile())
                lblFeedback.setText("Database backup successful");
            else
                lblFeedback.setText("Error backing up database");
        }
    }//GEN-LAST:event_btnBackUpDataActionPerformed
    /**
     * Load View Vendors window. Hides this window.
     * @param evt ActionEvent, passed by default but not used
     */
    private void btnViewVendorsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewVendorsActionPerformed
    {//GEN-HEADEREND:event_btnViewVendorsActionPerformed
        ViewVendors newWindow = new ViewVendors(this);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewVendorsActionPerformed
    /**
     * Restore database data from binary file backup. Asks for confirmation from
     * the user.
     * @param evt ActionEvent, passed by default but not used
     */
    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRestoreActionPerformed
    {//GEN-HEADEREND:event_btnRestoreActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, 
                                            "Restore the database from the backup?", 
                                            "Confirm", 
                                            JOptionPane.YES_NO_OPTION);
        if (choice == 0)
        {   
            if (DatabaseBackup.readFromFile())
                lblFeedback.setText("Database restored!");
            else
                lblFeedback.setText("Error restoring database");
        }
    }//GEN-LAST:event_btnRestoreActionPerformed
    /**
     * Opens the help document pdf in a separate application
     * @param evt ActionEvent, passed by default but not used
     */
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHelpActionPerformed
    {//GEN-HEADEREND:event_btnHelpActionPerformed
        try
        {
            File file = new File(HELPDOC);
            Desktop.getDesktop().open(file);
        }
        catch (IOException ioEx)
        {
            lblFeedback.setText("Error reading Help document");
            System.err.println("Error opening file: " + HELPDOC);
        }
    }//GEN-LAST:event_btnHelpActionPerformed
    /**
     * Set all buttons to disabled except Help
     * For use when the database doesn't load
     */
    private void disableButtons()
    {
        btnAddVendor.setEnabled(false);
        btnViewVendors.setEnabled(false);
        btnBackUpData.setEnabled(false);
        btnRestore.setEnabled(false);
        btnHelp.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVendor;
    private javax.swing.JButton btnBackUpData;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnViewVendors;
    private javax.swing.JLabel imgIcon;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
