/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import io.DatabaseMethods;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import utilityclasses.Section;
import validation.Validation;

/**
 * Form fields panel for modifying vendor data
 * @author Link Jones
 * @version 1.0
 * @since 2021-11-24
 */
public class VendorFields extends javax.swing.JPanel
{
    private Section[] sectionList;
    /**
     * Creates new form VendorFields
     */
    public VendorFields()
    {
        initComponents();
        selectPermanentMember(); 
        showPermanentMemberFields();
        populateSectionDropDown(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGrpVendorType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtShopName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        drpSection = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radPermanent = new javax.swing.JRadioButton();
        radDayPass = new javax.swing.JRadioButton();
        lblDateJoined = new javax.swing.JLabel();
        txtDateJoined = new javax.swing.JTextField();
        lblPassDate = new javax.swing.JLabel();
        txtPassDate = new javax.swing.JTextField();
        chkFeePaid = new javax.swing.JCheckBox();
        lblFirstTime = new javax.swing.JLabel();
        chkFirstTime = new javax.swing.JCheckBox();
        lblFirstNameFeedback = new javax.swing.JLabel();
        lblLastNameFeedback = new javax.swing.JLabel();
        lblShopNameFeedback = new javax.swing.JLabel();
        lblMobileFeedback = new javax.swing.JLabel();
        lblEmailFeedback = new javax.swing.JLabel();
        lblDateJoinedFeedback = new javax.swing.JLabel();
        lblPassDateFeedback = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel1.setText("First name:");

        txtFirstName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setText("Last name:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel3.setText("Shop name:");

        txtShopName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel4.setText("Mobile:");

        txtMobile.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel5.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel6.setText("Section:");

        drpSection.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        drpSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel7.setText("Fee paid:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel9.setText("Vendor type:");

        btnGrpVendorType.add(radPermanent);
        radPermanent.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        radPermanent.setText("Permanent member");
        radPermanent.setToolTipText("Membership is paid annually and allows attendance on any market day");
        radPermanent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radPermanentActionPerformed(evt);
            }
        });

        btnGrpVendorType.add(radDayPass);
        radDayPass.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        radDayPass.setText("Day pass");
        radDayPass.setToolTipText("Allows for attendance on a single market day");
        radDayPass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radDayPassActionPerformed(evt);
            }
        });

        lblDateJoined.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblDateJoined.setText("Date joined:");
        lblDateJoined.setToolTipText("Date that the vendor first joined the craft market");

        txtDateJoined.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtDateJoined.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDateJoinedActionPerformed(evt);
            }
        });

        lblPassDate.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblPassDate.setText("Pass date:");
        lblPassDate.setToolTipText("Date that the single-day pass is valid for");

        txtPassDate.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtPassDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPassDateActionPerformed(evt);
            }
        });

        chkFeePaid.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        lblFirstTime.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblFirstTime.setText("First time:");
        lblFirstTime.setToolTipText("Is this the vendor's first time attending the craft market?");

        chkFirstTime.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        lblFirstNameFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblLastNameFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblShopNameFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblMobileFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblEmailFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblDateJoinedFeedback.setForeground(new java.awt.Color(255, 51, 51));

        lblPassDateFeedback.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShopNameFeedback)
                            .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(lblDateJoined)
                            .addComponent(lblPassDate)
                            .addComponent(lblFirstTime))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMobileFeedback)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmailFeedback)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateJoinedFeedback)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDateJoined, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(chkFirstTime, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkFeePaid, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(drpSection, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPassDate))
                                    .addComponent(lblPassDateFeedback)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(41, 41, 41)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(txtLastName)
                                .addComponent(txtShopName)
                                .addComponent(lblFirstNameFeedback)
                                .addComponent(lblLastNameFeedback))
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel9)
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radDayPass)
                                .addComponent(radPermanent)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {drpSection, txtDateJoined, txtFirstName, txtLastName, txtMobile, txtPassDate, txtShopName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(radPermanent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radDayPass)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblFirstNameFeedback)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addComponent(lblLastNameFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(lblShopNameFeedback)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMobileFeedback)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailFeedback)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(drpSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkFeePaid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateJoined)
                    .addComponent(txtDateJoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblDateJoinedFeedback)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassDate)
                    .addComponent(txtPassDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblPassDateFeedback)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstTime)
                    .addComponent(chkFirstTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFirstNameActionPerformed
    {//GEN-HEADEREND:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed
    /**
     * When the permanent member radio button is selected, change which fields
     * are visible
     * @param evt 
     */
    private void radPermanentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radPermanentActionPerformed
    {//GEN-HEADEREND:event_radPermanentActionPerformed
        showPermanentMemberFields();
    }//GEN-LAST:event_radPermanentActionPerformed

    private void txtDateJoinedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDateJoinedActionPerformed
    {//GEN-HEADEREND:event_txtDateJoinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateJoinedActionPerformed

    private void txtPassDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPassDateActionPerformed
    {//GEN-HEADEREND:event_txtPassDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassDateActionPerformed
    /**
     * When the day pass member radio button is selected, change which fields
     * are visible
     * @param evt 
     */
    private void radDayPassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radDayPassActionPerformed
    {//GEN-HEADEREND:event_radDayPassActionPerformed
        showDayPassMemberFields();
    }//GEN-LAST:event_radDayPassActionPerformed
    /**
     * Validate all inputs for the form fields and set feedback text if input
     * is invalid
     * @return true if all text field inputs are valid
     */
    public boolean validateTextInputs()
    {
        boolean valid = true;
        //if validation fails, show feedback text and validation will fail
        if (!Validation.validName(txtFirstName.getText()))
        {
            valid = false;
            lblFirstNameFeedback.setText("First name must be between 1-25 characters");
        }
        else //validation successful, clear feedback text
        {
            lblFirstNameFeedback.setText("");
        }
        if (!Validation.validName(txtLastName.getText()))
        {
            valid = false;
            lblLastNameFeedback.setText("Last name must be between 1-25 characters");
        }
        else
        {
            lblLastNameFeedback.setText("");
        }
        if (!Validation.validShopName(txtShopName.getText()))
        {
            valid = false;
            lblShopNameFeedback.setText("Shop name must be between 1-50 characters");
        }
        else
        {
            lblShopNameFeedback.setText("");
        }
        if (!Validation.validMobileNumber(txtMobile.getText()))
        {
            valid=false;
            lblMobileFeedback.setText("Mobile number must be 10 digits");
        }
        else
        {
            lblMobileFeedback.setText("");
        }
        if (!Validation.validEmailAddress(txtEmail.getText()))
        {
            valid = false;
            lblEmailFeedback.setText("Email address must be in the format: __@__.__");
        }
        else
        {
            lblEmailFeedback.setText("");
        }
        if (radPermanent.isSelected()) // valid fields for permanent members
        {
            if (!Validation.validDate(txtDateJoined.getText()))
            {
                System.out.println(txtDateJoined.getText());
                valid = false;
                lblDateJoinedFeedback.setText("Date must be in the format: yyyy-mm-dd");
            }
            else
            {
                lblDateJoinedFeedback.setText("");
            }
        }
        else //validate fields for day pass members
        {
            if (!Validation.validDate(txtPassDate.getText()))
            {
                valid = false;
                lblPassDateFeedback.setText("Date must be in the format: yyyy-mm-dd");
            }
            else
            {
                lblPassDateFeedback.setText("");
            }
        }    
        return valid;
    }
    /**
     * Fetch the list of sections from the database and use it to populate the 
     * section dropdown control
     * The Section class toString method returns only the section name for this
     * purpose, because the DefaultComboBoxModel uses it
     */
    private void populateSectionDropDown()
    {
        //fetch section data
        ArrayList<Section> sections = DatabaseMethods.getSectionList();
        //create an array from the arraylist of sections
        sectionList = new Section[sections.size()]; 
        for (int i=0; i<sections.size(); i++)
        {
            sectionList[i] = sections.get(i);
        }
        //initialise a combobox model with the section array and assign it
        //to the section combobox
        //each selection item is an object, with the displayed label using the
        //object's toString method
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(sectionList);
        drpSection.setModel(comboModel);
    }
    /**
     * show Date joined field and hide Pass date and First time fields
     */
    private void showPermanentMemberFields()
    {
        lblPassDate.setVisible(false);
        txtPassDate.setVisible(false);
        lblPassDateFeedback.setVisible(false);
        lblFirstTime.setVisible(false);
        chkFirstTime.setVisible(false);
        lblDateJoined.setVisible(true);
        txtDateJoined.setVisible(true);
        lblDateJoinedFeedback.setVisible(true);
    }
    /**
     * Hide Date joined field and show Pass date and First time fields
     */
    private void showDayPassMemberFields()
    {
        lblDateJoined.setVisible(false);
        txtDateJoined.setVisible(false);
        lblDateJoinedFeedback.setVisible(false);
        lblPassDate.setVisible(true);
        txtPassDate.setVisible(true);
        lblPassDateFeedback.setVisible(true);
        lblFirstTime.setVisible(true);
        chkFirstTime.setVisible(true);
    }
    /**
     * Select the Permanent Member radio button and change the form to show 
     * relevant fields
     */
    public void selectPermanentMember()
    {
        showPermanentMemberFields();
        radPermanent.setSelected(true);
    }
    /**
     * Select the Day Pass Member radio button and change the form to show 
     * relevant fields
     */
    public void selectDayPassMember()
    {
        showDayPassMemberFields();
        radDayPass.setSelected(true);
    }
    /**
     * 
     * @return the section ID of the highlighted option of drpSection
     */
    public int getSelectedSection()
    {
        return ((Section) drpSection.getSelectedItem()).getId();
    }
    /**
     * Find the section in sectionList that matches sectionID and set it as
     * drpSelection's selected item
     * @param sectionID 
     */
    public void setSelectedSection(int sectionID)
    {
        Section s = null;
        for (int i=0; i<sectionList.length; i++)
        {
            if (sectionList[i].getId() == sectionID)
                s = sectionList[i];
        }
        drpSection.setSelectedItem(s); 
    }
    /**
     * Reset all fields to their default state
     */
    public void clearFields()
    {
        selectPermanentMember();
        txtFirstName.setText("");
        txtLastName.setText("");
        txtShopName.setText("");
        txtMobile.setText("");
        txtEmail.setText("");
        chkFeePaid.setSelected(false);
        txtDateJoined.setText("");
        chkFirstTime.setSelected(false);
        txtPassDate.setText("");
    }
    /**
     * 
     * @return shop name text field
     */
    public JTextField getTxtShopName()
    {
        return txtShopName;
    }
    /**
     * 
     * @return fee paid checkbox
     */
    public JCheckBox getChkFeePaid()
    {
        return chkFeePaid;
    }
    /**
     * 
     * @return first time checkbox 
     */
    public JCheckBox getChkFirstTime()
    {
        return chkFirstTime;
    }
    /**
     * 
     * @return section dropdown box 
     */
    public JComboBox<String> getDrpSection()
    {
        return drpSection;
    }
    /**
     * 
     * @return day pass radio button 
     */
    public JRadioButton getRadDayPass()
    {
        return radDayPass;
    }
    /**
     * 
     * @return Permanent member radio button
     */
    public JRadioButton getRadPermanent()
    {
        return radPermanent;
    }
    /**
     * 
     * @return date joined text field
     */
    public JTextField getTxtDateJoined()
    {
        return txtDateJoined;
    }
    /**
     * 
     * @return email text field 
     */
    public JTextField getTxtEmail()
    {
        return txtEmail;
    }
    /**
     * 
     * @return first name text field 
     */
    public JTextField getTxtFirstName()
    {
        return txtFirstName;
    }
    /**
     * 
     * @return last name text field
     */
    public JTextField getTxtLastName()
    {
        return txtLastName;
    }
    /**
     * 
     * @return mobile text field 
     */
    public JTextField getTxtMobile()
    {
        return txtMobile;
    }
    /**
     * 
     * @return pass date text field 
     */
    public JTextField getTxtPassDate()
    {
        return txtPassDate;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpVendorType;
    private javax.swing.JCheckBox chkFeePaid;
    private javax.swing.JCheckBox chkFirstTime;
    private javax.swing.JComboBox<String> drpSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDateJoined;
    private javax.swing.JLabel lblDateJoinedFeedback;
    private javax.swing.JLabel lblEmailFeedback;
    private javax.swing.JLabel lblFirstNameFeedback;
    private javax.swing.JLabel lblFirstTime;
    private javax.swing.JLabel lblLastNameFeedback;
    private javax.swing.JLabel lblMobileFeedback;
    private javax.swing.JLabel lblPassDate;
    private javax.swing.JLabel lblPassDateFeedback;
    private javax.swing.JLabel lblShopNameFeedback;
    private javax.swing.JRadioButton radDayPass;
    private javax.swing.JRadioButton radPermanent;
    private javax.swing.JTextField txtDateJoined;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPassDate;
    private javax.swing.JTextField txtShopName;
    // End of variables declaration//GEN-END:variables
}
