/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import io.DatabaseMethods;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import ui.SearchVendorTableModel.SearchOption;
import utilityclasses.Vendor;

/**
 * View Vendors window for the Vendor database application
 * Allows viewing all vendors, searching, deleting, and opening the update vendor
 * menu
 * @author Link Jones
 * @version 1.0
 * @since 2021-11-24
 */
public class ViewVendors extends javax.swing.JFrame
{
    private MainGUI parent;
    private int selectedRow = -1; //initialise at -1 to indicate no selection
    private SearchOption searchOption = SearchOption.BY_SHOP_NAME;
    private VendorTableModel vendorTableModel; //keeps a list of all vendors
    private SearchVendorTableModel searchTable; //keeps a list of vendor search results
    /**
     * Creates new form ViewMembers
     */
    public ViewVendors(MainGUI parent)
    {
        this.parent = parent;
        initComponents();
        this.setBounds(100, 100, 700, 640);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //initialise the table models
        searchTable = new SearchVendorTableModel();
        vendorTableModel = new VendorTableModel();
        tblVendors.setModel(vendorTableModel); //view all vendors by default
        tblVendors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //keep track of currently selected row
        ListSelectionModel listSelectedRow = tblVendors.getSelectionModel();
        listSelectedRow.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e)
                {
                    ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                    selectedRow = lsm.getMinSelectionIndex();
                }
        });
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGrpSearchBy = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendors = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDetails = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClearSearch = new javax.swing.JButton();
        radLastName = new javax.swing.JRadioButton();
        radFirstName = new javax.swing.JRadioButton();
        radShopName = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVendors.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        tblVendors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVendors.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblVendorsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVendors);

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        lblTitle.setText("All Vendors");

        btnSearch.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel1.setText("Search for a vendor: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnDetails.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDetailsActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblFeedback.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        lblFeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnClearSearch.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnClearSearch.setText("Clear Search");
        btnClearSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearSearchActionPerformed(evt);
            }
        });

        btnGrpSearchBy.add(radLastName);
        radLastName.setText("Last name");
        radLastName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radLastNameActionPerformed(evt);
            }
        });

        btnGrpSearchBy.add(radFirstName);
        radFirstName.setText("First name");
        radFirstName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radFirstNameActionPerformed(evt);
            }
        });

        btnGrpSearchBy.add(radShopName);
        radShopName.setSelected(true);
        radShopName.setText("Shop name");
        radShopName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radShopNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Search by:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(radShopName)
                .addGap(18, 18, 18)
                .addComponent(radFirstName)
                .addGap(18, 18, 18)
                .addComponent(radLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnClearSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radLastName)
                            .addComponent(radFirstName)
                            .addComponent(radShopName)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addComponent(lblTitle))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(lblFeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFeedback)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Close the current window and reopen the parent window
     * @param evt 
     */
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    /**
     * Get the currently selected vendor information and open a new Update Vendor
     * window displaying its data. Hides this window.
     * @param evt 
     */
    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetailsActionPerformed
    {//GEN-HEADEREND:event_btnDetailsActionPerformed
        if (selectedRow == -1) //check if any vendor has been selected
        {
            lblFeedback.setText("No record selected");
        }
        else
        {
            //Get the current table model (all vendors or search results)
            VendorTableModel currentTable = (VendorTableModel) tblVendors.getModel();
            //get the vendor for the current row and send it to UpdateVendor window
            Vendor v = currentTable.getRow(selectedRow);
            new UpdateVendor(this, v, currentTable);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed
    /**
     * Delete the selected vendor.
     * Fetch the vendor corresponding to the selected row and then display a 
     * confirm dialog. If the user confirms, delete the vendor from the database.
     * @param evt 
     */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        int vendorID = vendorTableModel.getRow(selectedRow).getId(); //get id of currently selected vendor record
        //confirm with user
        int choice = JOptionPane.showConfirmDialog(this, 
                "Do you really want to delete the vendor with ID #" + vendorID + "?", 
                "Confirm", 
                JOptionPane.YES_NO_OPTION);
        if (choice == 0) //yes option
        {
            //try to delete the vendor
            if (DatabaseMethods.deleteVendor(vendorID))
            {
                lblFeedback.setText("Vendor deleted");
                refresh();
            }
            else //deleting failed
            {
                lblFeedback.setText("Error deleting vendor");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    /**
     * Search the vendor data for a matching record based on the search option.
     * Fetch the search option from the search option radio button and set the
     * vendor table view to the search results table model.
     * @param evt 
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        searchTable.searchVendors(txtSearch.getText(), searchOption);
        tblVendors.setModel(searchTable);
        searchTable.fireTableDataChanged();
        selectedRow = -1;
    }//GEN-LAST:event_btnSearchActionPerformed
    /**
     * Display all vendors in the vendor table view
     * @param evt 
     */
    private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearSearchActionPerformed
    {//GEN-HEADEREND:event_btnClearSearchActionPerformed
        tblVendors.setModel(vendorTableModel);
        txtSearch.setText("");
    }//GEN-LAST:event_btnClearSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSearchActionPerformed
    {//GEN-HEADEREND:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
    /**
     * Select the radio button for "Shop name"
     * Set the search option to "By shop name"
     * @param evt 
     */
    private void radShopNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radShopNameActionPerformed
    {//GEN-HEADEREND:event_radShopNameActionPerformed
        this.searchOption = SearchOption.BY_SHOP_NAME;
    }//GEN-LAST:event_radShopNameActionPerformed
    /**
     * Select the radio button for "First name"
     * Set the search option to "By first name"
     * @param evt 
     */
    private void radFirstNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radFirstNameActionPerformed
    {//GEN-HEADEREND:event_radFirstNameActionPerformed
        this.searchOption = SearchOption.BY_FIRST_NAME;
    }//GEN-LAST:event_radFirstNameActionPerformed
    /**
     * Select the radio button for "Last name"
     * Set the search option to "By last name"
     * @param evt 
     */
    private void radLastNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radLastNameActionPerformed
    {//GEN-HEADEREND:event_radLastNameActionPerformed
        this.searchOption = SearchOption.BY_LAST_NAME;
    }//GEN-LAST:event_radLastNameActionPerformed

    private void tblVendorsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblVendorsMouseClicked
    {//GEN-HEADEREND:event_tblVendorsMouseClicked
        //none
    }//GEN-LAST:event_tblVendorsMouseClicked
    /**
     * Refresh the table view by re-fetching the database data for both the 
     * all vendors table and search results table
     */
    public void refresh()
    {
        //refresh search table
        this.searchTable.refreshData();
        //refresh vendor table
        this.vendorTableModel.fetchData();
        this.vendorTableModel.fireTableDataChanged();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearSearch;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetails;
    private javax.swing.ButtonGroup btnGrpSearchBy;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radFirstName;
    private javax.swing.JRadioButton radLastName;
    private javax.swing.JRadioButton radShopName;
    private javax.swing.JTable tblVendors;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
